Переименовал pid_number в process_id, и поменял его тип ,на целое число.  Переименовал pid_name в  process_name.
Nikitadocker/study_python pull request #2
Opened 2024-02-19 15:11 UTC by Nikitadocker

2024-02-19 17:14 UTC, mossad-zika commented
- Стоит ли переименовать в этой программе что-то ещё из перменных?
- Не кажется ли тебе странным что два ключа в финальном JSON файле выглядят однообразно, а третий - совсем по-другому?

2024-02-20 15:53 UTC, Nikitadocker commented
> * Стоит ли переименовать в этой программе что-то ещё из перменных?
> * Не кажется ли тебе странным что два ключа в финальном JSON файле выглядят однообразно, а третий - совсем по-другому?

Переименовал Prime or Composite на prime_or_composite, что бы 3 ключ был похож на остальные

2024-02-20 18:33 UTC, mossad-zika requested changes
Предлагаю такую структуру
```
{
  "Is Prime": false,
  "Process Name": "/bin/chrome",
  "Process Number": 12
}
```

2024-02-23 08:24 UTC, Nikitadocker commented
> Предлагаю такую структуру
> 
> ```
> {
>   "Is Prime": false,
>   "Process Name": "/bin/chrome",
>   "Process Number": 12
> }
> ```

Поменял имя ключа с pid_number на Process Number, pid_name на Processs Name.
Не согласен со структурой "Is Prime": false.
Есть число один,которое не является ни простым,ни сложным,данная структура не выглядит как подходящая
Предлагаю оставить cтруктуру "Prime or Composite"

2024-02-25 06:05 UTC, Nikitadocker commented
> > Предлагаю такую структуру
> > ```
> > {
> >   "Is Prime": false,
> >   "Process Name": "/bin/chrome",
> >   "Process Number": 12
> > }
> > ```
> 
> Поменял имя ключа с pid_number на Process Number, pid_name на Processs Name. Не согласен со структурой "Is Prime": false. Есть число один,которое не является ни простым,ни сложным,данная структура не выглядит как подходящая Предлагаю оставить cтруктуру "Prime or Composite"

Еще раз переделал структуру json.
Добавил ключи Is Prime и Is Composite. Значение данных ключей могут быть false или true

2024-02-28 17:44 UTC, merged